name: Push tags to docker github repository
on:
  push:
    tags:
      - '*'
env:
  TARGET_BRANCH: 1.2.x
  DOCKER_REPO_GIT_URL: "exo-docker/jitsi-call"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: ${{ env.DOCKER_REPO_GIT_URL }}
          ref: ${{ env.TARGET_BRANCH }}
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.SWF_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SWF_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Create tag
        run: |
          echo "Current tag: ${RELEASE_VERSION}"
          git config --global user.name 'eXo Software Factory'
          git config --global user.email 'exo-swf@exoplatform.com'
          sed -Ei "s/JITSI_CALL_VERSION=.*/JITSI_CALL_VERSION=${RELEASE_VERSION}/" Dockerfile
          git add Dockerfile
          git commit -m "Release ${RELEASE_VERSION}"
          git tag ${RELEASE_VERSION}_0
          git push origin ${RELEASE_VERSION}_0:${RELEASE_VERSION}_0
