name: Push tags to docker github repository
on:
  push:
    tags:
      - '*'
env:
  TARGET_BRANCH: master
  DOCKER_REPO_GIT_URL: "git@github.com:exo-docker/jitsi-call.git"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create tag
        run: |
          current_tag=${GITHUB_REF##*/}
          echo "Current tag: ${current_tag}"
          git config --global user.name 'eXo Software Factory'
          git config --global user.email 'exo-swf@exoplatform.com'
          git clone ${DOCKER_REPO_GIT_URL} /tmp/image
          pushd /tmp/image
          git checkout ${TARGET_BRANCH}
          sed -Ei "s/JITSI_CALL_VERSION=.*/JITSI_CALL_VERSION=${current_tag}/" Dockerfile
          git add Dockerfile
          git commit -m "Release ${current_tag}"
          git tag ${current_tag}_0
          git push origin ${current_tag}_0:${current_tag}_0
